<?php
require_once __DIR__ . '/includes/auth_check.php';
require_once __DIR__ . '/../config/db.php';
$studentId = (int) $_SESSION['student_id'];
$stmt = $pdo->prepare('SELECT c.*, (SELECT COUNT(*) FROM subjects s WHERE s.course_id = c.id AND s.status = \'active\') subject_count FROM courses c JOIN student_courses sc ON sc.course_id = c.id WHERE sc.student_id = ? AND c.status = \'active\' ORDER BY c.name'); $stmt->execute([$studentId]); $courses = $stmt->fetchAll();
$stmt = $pdo->prepare("SELECT sp.*, c.name course_name, s.name subject_name, r.title resource_title, r.file_path, r.external_url, q.title quiz_title, q.id available_quiz_id, (SELECT qa.score FROM quiz_attempts qa WHERE qa.quiz_id = q.id AND qa.student_id = ? ORDER BY qa.attempted_at DESC LIMIT 1) latest_score, (SELECT qa.total_marks FROM quiz_attempts qa WHERE qa.quiz_id = q.id AND qa.student_id = ? ORDER BY qa.attempted_at DESC LIMIT 1) latest_total FROM study_plans sp JOIN student_courses sc ON sc.course_id = sp.course_id AND sc.student_id = ? JOIN courses c ON c.id = sp.course_id LEFT JOIN subjects s ON s.id = sp.subject_id LEFT JOIN resources r ON r.id = sp.resource_id LEFT JOIN quizzes q ON q.id = sp.quiz_id AND q.status = 'published' ORDER BY c.name, sp.day_number, sp.id"); $stmt->execute([$studentId, $studentId, $studentId]); $plans = $stmt->fetchAll();
$plansByCourse = []; foreach ($plans as $plan) { $plansByCourse[$plan['course_id']][] = $plan; }
$studentPageTitle = 'My Study Plan'; include __DIR__ . '/includes/header.php';
?>
<section class="portal-hero"><p class="eyebrow">Welcome back, <?= e($_SESSION['student_name']) ?></p><h1>Your learning path</h1><p>Follow each course day by day, open the lesson resources, and complete quizzes when you are ready.</p></section>
<?php if (!$courses): ?><div class="empty-state"><h2>No course assigned yet</h2><p>Ask your administrator to enroll you in a course.</p></div><?php endif; ?>
<?php foreach ($courses as $course): ?><section class="course-section"><div class="course-heading"><div><span class="course-kicker"><?= e($course['subject_count']) ?> subjects</span><h2><?= e($course['name']) ?></h2><p><?= e($course['description']) ?></p></div></div><div class="timeline">
<?php foreach ($plansByCourse[$course['id']] ?? [] as $plan): ?><article class="study-day"><div class="day-badge">Day <?= e($plan['day_number']) ?></div><div class="day-content"><span class="subject-name"><?= e($plan['subject_name'] ?: 'Course activity') ?></span><h3><?= e($plan['title']) ?></h3><p><?= e($plan['description']) ?></p><div class="day-actions"><?php if ($plan['resource_title']): ?><?php $resourceUrl = $plan['file_path'] ? site_url($plan['file_path']) : $plan['external_url']; ?><a class="secondary-button" target="_blank" href="<?= e($resourceUrl) ?>">↓ <?= e($plan['resource_title']) ?></a><?php endif; ?><?php if ($plan['available_quiz_id']): ?><a class="button compact" href="<?= e(site_url('frontend/quiz.php?id=' . $plan['available_quiz_id'])) ?>">Attempt <?= e($plan['quiz_title']) ?></a><?php if ($plan['latest_score'] !== null): ?><span class="score-chip">Latest: <?= e($plan['latest_score']) ?>/<?= e($plan['latest_total']) ?></span><?php endif; ?><?php endif; ?></div></div></article><?php endforeach; ?>
<?php if (empty($plansByCourse[$course['id']])): ?><div class="empty-state compact-empty">The study plan for this course is being prepared.</div><?php endif; ?></div></section><?php endforeach; ?>
<?php include __DIR__ . '/includes/footer.php'; ?>
