<?php
require_once __DIR__ . '/../../includes/auth_check.php';
require_once __DIR__ . '/../../config/db.php';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf();
    if (($_POST['action'] ?? '') === 'delete') {
        $pdo->prepare('DELETE FROM study_plans WHERE id = ?')->execute([(int) $_POST['id']]); flash('success', 'Study-plan item deleted.');
    } else {
        $courseId = (int) $_POST['course_id'];
        $subjectId = (int) $_POST['subject_id'] ?: null; $resourceId = (int) $_POST['resource_id'] ?: null; $quizId = (int) $_POST['quiz_id'] ?: null;
        if ($subjectId) { $check = $pdo->prepare('SELECT COUNT(*) FROM subjects WHERE id = ? AND course_id = ?'); $check->execute([$subjectId, $courseId]); if (!$check->fetchColumn()) { $subjectId = null; } }
        if ($resourceId) { $check = $pdo->prepare('SELECT COUNT(*) FROM resources r JOIN subjects s ON s.id = r.subject_id WHERE r.id = ? AND s.course_id = ?'); $check->execute([$resourceId, $courseId]); if (!$check->fetchColumn()) { $resourceId = null; } }
        if ($quizId) { $check = $pdo->prepare('SELECT COUNT(*) FROM quizzes q JOIN subjects s ON s.id = q.subject_id WHERE q.id = ? AND s.course_id = ?'); $check->execute([$quizId, $courseId]); if (!$check->fetchColumn()) { $quizId = null; } }
        $pdo->prepare('INSERT INTO study_plans (course_id, subject_id, resource_id, quiz_id, day_number, title, description) VALUES (?, ?, ?, ?, ?, ?, ?)')->execute([$courseId, $subjectId, $resourceId, $quizId, max(1, (int) $_POST['day_number']), trim($_POST['title']), trim($_POST['description'] ?? '')]); flash('success', 'Day added to the study plan.');
    }
    redirect('modules/study-plans/index.php');
}
$courses = $pdo->query('SELECT id, name FROM courses WHERE status = \'active\' ORDER BY name')->fetchAll();
$subjects = $pdo->query('SELECT s.id, s.name, s.course_id, c.name course_name FROM subjects s JOIN courses c ON c.id = s.course_id WHERE s.status = \'active\' ORDER BY c.name, s.name')->fetchAll();
$resources = $pdo->query('SELECT r.id, r.title, s.course_id, s.name subject_name FROM resources r JOIN subjects s ON s.id = r.subject_id ORDER BY r.title')->fetchAll();
$quizzes = $pdo->query('SELECT q.id, q.title, s.course_id, s.name subject_name FROM quizzes q JOIN subjects s ON s.id = q.subject_id ORDER BY q.title')->fetchAll();
$plans = $pdo->query('SELECT sp.*, c.name course_name, s.name subject_name, r.title resource_title, q.title quiz_title FROM study_plans sp JOIN courses c ON c.id = sp.course_id LEFT JOIN subjects s ON s.id = sp.subject_id LEFT JOIN resources r ON r.id = sp.resource_id LEFT JOIN quizzes q ON q.id = sp.quiz_id ORDER BY c.name, sp.day_number, sp.id')->fetchAll();
$pageTitle = 'Study Plans'; $active = 'study-plans'; include __DIR__ . '/../../includes/header.php';
?>
<div class="row g-3"><div class="col-xl-4"><div class="panel"><h2 class="h5 mb-3">Add Study Day</h2><form method="post"><?= csrf_field() ?>
<div class="mb-3"><label class="form-label">Course</label><select class="form-select" name="course_id" required><option value="">Select course</option><?php foreach ($courses as $course): ?><option value="<?= e($course['id']) ?>"><?= e($course['name']) ?></option><?php endforeach; ?></select></div><div class="mb-3"><label class="form-label">Day number</label><input class="form-control" type="number" min="1" name="day_number" required></div><div class="mb-3"><label class="form-label">Day title</label><input class="form-control" name="title" placeholder="Introduction and first reading" required></div>
<div class="mb-3"><label class="form-label">Subject</label><select class="form-select" name="subject_id"><option value="">Optional</option><?php foreach ($subjects as $subject): ?><option value="<?= e($subject['id']) ?>"><?= e($subject['course_name'] . ' — ' . $subject['name']) ?></option><?php endforeach; ?></select></div><div class="mb-3"><label class="form-label">Resource</label><select class="form-select" name="resource_id"><option value="">Optional</option><?php foreach ($resources as $resource): ?><option value="<?= e($resource['id']) ?>"><?= e($resource['subject_name'] . ' — ' . $resource['title']) ?></option><?php endforeach; ?></select></div><div class="mb-3"><label class="form-label">Quiz</label><select class="form-select" name="quiz_id"><option value="">Optional</option><?php foreach ($quizzes as $quiz): ?><option value="<?= e($quiz['id']) ?>"><?= e($quiz['subject_name'] . ' — ' . $quiz['title']) ?></option><?php endforeach; ?></select></div><div class="mb-3"><label class="form-label">Instructions</label><textarea class="form-control" name="description" rows="3"></textarea></div><button class="btn btn-primary">Add to Plan</button></form></div></div>
<div class="col-xl-8"><div class="panel"><h2 class="h5 mb-3">Day-wise Course Plans</h2><div class="table-responsive"><table class="table table-hover align-middle data-table"><thead><tr><th>Day</th><th>Course</th><th>Plan</th><th>Attached</th><th></th></tr></thead><tbody><?php foreach ($plans as $plan): ?><tr><td><span class="badge text-bg-primary">Day <?= e($plan['day_number']) ?></span></td><td><?= e($plan['course_name']) ?><div class="small text-secondary"><?= e($plan['subject_name'] ?: 'General') ?></div></td><td><strong><?= e($plan['title']) ?></strong><div class="small text-secondary"><?= e($plan['description']) ?></div></td><td><?php if ($plan['resource_title']): ?><div><i class="bi bi-file-earmark"></i> <?= e($plan['resource_title']) ?></div><?php endif; ?><?php if ($plan['quiz_title']): ?><div><i class="bi bi-ui-checks"></i> <?= e($plan['quiz_title']) ?></div><?php endif; ?><?php if (!$plan['resource_title'] && !$plan['quiz_title']): ?>—<?php endif; ?></td><td><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= e($plan['id']) ?>"><button class="btn btn-sm btn-outline-danger js-delete">Delete</button></form></td></tr><?php endforeach; ?></tbody></table></div></div></div></div>
<?php include __DIR__ . '/../../includes/footer.php'; ?>
