<?php
require_once __DIR__ . '/../../includes/auth_check.php';
require_once __DIR__ . '/../../config/db.php';
$quizId = (int) ($_GET['quiz_id'] ?? $_POST['quiz_id'] ?? 0);
$stmt = $pdo->prepare('SELECT q.*, s.name subject_name FROM quizzes q JOIN subjects s ON s.id = q.subject_id WHERE q.id = ?'); $stmt->execute([$quizId]); $quiz = $stmt->fetch();
if (!$quiz) { flash('error', 'Quiz not found.'); redirect('modules/quizzes/index.php'); }
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf();
    if (($_POST['action'] ?? '') === 'delete') { $pdo->prepare('DELETE FROM quiz_questions WHERE id = ? AND quiz_id = ?')->execute([(int) $_POST['id'], $quizId]); flash('success', 'Question deleted.'); }
    else { $correct = in_array($_POST['correct_option'] ?? '', ['A','B','C','D'], true) ? $_POST['correct_option'] : 'A'; $pdo->prepare('INSERT INTO quiz_questions (quiz_id, question_text, option_a, option_b, option_c, option_d, correct_option, marks) VALUES (?, ?, ?, ?, ?, ?, ?, ?)')->execute([$quizId, trim($_POST['question_text']), trim($_POST['option_a']), trim($_POST['option_b']), trim($_POST['option_c']), trim($_POST['option_d']), $correct, max(1, (int) $_POST['marks'])]); flash('success', 'Question added.'); }
    redirect('modules/quizzes/questions.php?quiz_id=' . $quizId);
}
$stmt = $pdo->prepare('SELECT * FROM quiz_questions WHERE quiz_id = ? ORDER BY id'); $stmt->execute([$quizId]); $questions = $stmt->fetchAll();
$pageTitle = 'Quiz Questions'; $active = 'quizzes'; include __DIR__ . '/../../includes/header.php';
?>
<div class="mb-3"><a href="<?= e(url('modules/quizzes/index.php')) ?>" class="btn btn-outline-secondary">← Back to quizzes</a></div><div class="row g-3"><div class="col-xl-5"><div class="panel"><h2 class="h5"><?= e($quiz['title']) ?></h2><p class="text-secondary"><?= e($quiz['subject_name']) ?></p><form method="post"><?= csrf_field() ?><input type="hidden" name="quiz_id" value="<?= e($quizId) ?>"><div class="mb-3"><label class="form-label">Question</label><textarea class="form-control" name="question_text" rows="3" required></textarea></div><?php foreach (['A','B','C','D'] as $option): ?><div class="mb-2"><label class="form-label">Option <?= $option ?></label><input class="form-control" name="option_<?= strtolower($option) ?>" required></div><?php endforeach; ?><div class="row g-2 mt-1"><div class="col-6"><label class="form-label">Correct option</label><select class="form-select" name="correct_option"><?php foreach (['A','B','C','D'] as $option): ?><option><?= $option ?></option><?php endforeach; ?></select></div><div class="col-6"><label class="form-label">Marks</label><input class="form-control" type="number" min="1" name="marks" value="1"></div></div><button class="btn btn-primary mt-3">Add Question</button></form></div></div>
<div class="col-xl-7"><div class="panel"><h2 class="h5 mb-3"><?= count($questions) ?> Questions</h2><?php foreach ($questions as $index => $question): ?><div class="border rounded p-3 mb-3"><div class="d-flex justify-content-between"><strong><?= $index + 1 ?>. <?= e($question['question_text']) ?></strong><form method="post"><?= csrf_field() ?><input type="hidden" name="quiz_id" value="<?= e($quizId) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= e($question['id']) ?>"><button class="btn btn-sm btn-outline-danger js-delete">Delete</button></form></div><div class="small text-secondary mt-2">A. <?= e($question['option_a']) ?> · B. <?= e($question['option_b']) ?> · C. <?= e($question['option_c']) ?> · D. <?= e($question['option_d']) ?></div><span class="badge text-bg-success mt-2">Answer: <?= e($question['correct_option']) ?> · <?= e($question['marks']) ?> marks</span></div><?php endforeach; ?><?php if (!$questions): ?><p class="text-secondary">No questions added yet.</p><?php endif; ?></div></div></div>
<?php include __DIR__ . '/../../includes/footer.php'; ?>
